name: Test

on:
  pull_request:
    branches:
      - master
  release:
    types: [released, prereleased]
  push:
    tags:
      - '*'
    branches:
      - '*'
  create:
  delete:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: echo true

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: echo true

  notify:
    runs-on: ubuntu-latest
    needs: [test, lint]
    if: always()
    steps:
      - uses: actions/checkout@v2
      - name: Test Output
        uses: ./ # Uses an action in the root directory
        with:
          platforms: cliq
        env:
          CLIQ_WEBHOOK_TOKEN: ${{ secrets.CLIQ_WEBHOOK_TOKEN }}
          CLIQ_CHANNEL: ${{ secrets.CLIQ_CHANNEL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
